config/routes.rb
FlexibleForm::Application.routes.draw do

  root :to => 'home#home'

  match '/save', to: 'home#create_submission', via: :post
  match '/end', to: 'home#end'

  match '/dashboard', to: 'admin#dashboard'

  match '/delete/:visit_id', to: 'admin#destroy_visit', via: :delete

  match '/dashboard/edit_texts/:page', to: 'admin#text_edit', as: 'text_edit'
  match '/dashboard/update_texts', to: 'admin#update_texts', via: :put, as: 'update_text'

  match '/dashboard/edit_email_template', to: 'admin#email_edit', as: 'email_edit'
  match '/dashboard/update_email_template', to: 'admin#update_email', via: :put, as: 'update_email'

  match '/dashboard/export', to: 'admin#export', as: :download_export
  
  match '/fb/:token', to: 'feedbacks#land', as: :feedback

end

app/views/admin/_visit_row.html.erb
<tr>
	<td>
		<%= v.id %> 
		<%= link_to "elimina", { controller: "admin", action: "destroy_visit", visit_id: v.id, order: @order }, method: :delete %>
	</td>
	<td><%= v.operative_system %></td>
	<!-- <td><%#= v.os_version %></td> -->
	<td><%= v.ip_address %></td>
	<!-- <td><%#= v.user_agent %></td> -->
	<td><%= v.created_at %></td>
	<% if s = v.submission %>
		<td><%= s.email %></td>
		<td><%= s.name %></td>
		<td><%= s.location %></td>
		<!-- <td><%#= s.token %></td>
		<%# if s.feedback  %>
			<td><%#= s.feedback.created_at %></td>
			<td><%#= s.feedback.humanized_delta %></td>
		<%# end %> -->
	<% end %>
	
</tr>

app/views/admin/dashboard.html.erb
<% provide(:title, "#{UserConfig::APP_TITLE} Dashboard") %>


<div class="dashboard_block">
	<span>Visite: <%= @visits.count %></span> - 
	<span>Iscrizioni: <%= @submission_count %></span>
</div>
<br>

<div class="dashboard_block">
	<span class="dashboard_block_label">Esporta le iscrizioni:</span>
	<%= link_to "scarica come CSV", download_export_path(format: :csv), class: "btn btn-primary btn-small button-spaced" %>
	<%= link_to "scarica come XLS", download_export_path(format: :xls), class: "btn btn-primary btn-small button-spaced" %>
	<%#= link_to "scarica come CSV", "#", class: "btn btn-primary btn-small button-spaced", onclick: "alert('Work in progress')" %>
	<%#= link_to "scarica come XLS", "#", class: "btn btn-primary btn-small button-spaced", onclick: "alert('Work in progress')" %>
</div>
<br>

<div class="dashboard_block">
	<span class="dashboard_block_label">Modifica i testi:</span>
	<%= link_to page_name("home"), text_edit_path(page: "home"), class: "btn btn-danger btn-small button-spaced" %>
	<%= link_to page_name("end"), text_edit_path(page: "end"), class: "btn btn-danger btn-small button-spaced" %>
	<%#= link_to page_name("land"), text_edit_path(page: "land"), class: "btn btn-danger btn-small button-spaced" %>
	<%#= link_to page_name("fb_error"), text_edit_path(page: "fb_error"), class: "btn btn-danger btn-small button-spaced" %>
	<%= link_to "Template eMail", email_edit_path, class: "btn btn-danger btn-small button-spaced" %>
</div>
<br>




<hr>

<div class="container">
	<table id="visit-table">
		<tr>
			<th>ID visita</th>
			<th>OS <%= caret_tag :os %></th>
			<!-- <th>Versione OS</th> -->
			<th>Indirizzo IP</th>
			<!-- <th>User Agent</th> -->
			<th>Data <%= caret_tag :date %></th>
			<th>email <%= caret_tag :email %></th>
			<th>nome</th>
			<th>posizione <%= caret_tag :location %></th>
			<!-- <th>token</th>
			<th>feedback <%#= caret_tag :feedback %></th>
			<th>&Delta;-t (iscrizione-feedback) <%#= caret_tag :delta %></th> -->
		</tr>
		<% @visits.each do |v| %>
			<%= render 'visit_row', v: v %>
		<% end %>
	</table>
</div>

app/views/admin/email_edit.html.erb
<% provide(:title, @title) %>
<h2>Modifica i testi</h2>

<%= link_to "back", :back, class: "btn" %>
<hr>

<div>
	<%= form_for @template, url: { action: 'update_email' } do |f| %>
		<%= render 'shared/error_messages', object: f.object %>

		<%= f.label :subject, 'email object' %>
		<%= f.text_field :subject %>

		<%= f.label :body, 'Email body' %>
		<%= f.text_area :body, rows: 8 %>
		<div>
			Within the body you can use these tags:
			<ul>
				<li><code>[name]</code>: This will be replaced by the name of the recipient, id they have provided it. Otherwise it will be used the fallback string: "<%= UserConfig::FALLBACK_USERNAME %>".</li>
				<li><code>[email]</code>: the email address the mail will be sent to.</li>
			</ul>
		</div><br>

		<%= f.label :style, 'CSS (Optional. The mail template already has a default style)' %>
		<%= f.text_area :style, rows: 8 %>


		<%= f.submit 'Save', class: 'btn btn-primary btn_tom' %>
	<% end %>

</div>

app/views/admin/export.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">id</Data></Cell>
        <Cell><Data ss:Type="String">email</Data></Cell>
        <Cell><Data ss:Type="String">name</Data></Cell>
        <Cell><Data ss:Type="String">location</Data></Cell>
        <!-- <Cell><Data ss:Type="String">token</Data></Cell> -->
        <Cell><Data ss:Type="String">created_at</Data></Cell>
      </Row>
    <% @submissions.each do |submission| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= submission.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= submission.email %></Data></Cell>
        <Cell><Data ss:Type="String"><%= submission.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= submission.location %></Data></Cell>
        <!-- <Cell><Data ss:Type="String"><%#= submission.token %></Data></Cell> -->
        <Cell><Data ss:Type="String"><%= submission.created_at %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/admin/text_edit.html.erb
<% provide(:title, "FlexibleForm - Settings") %>
<h2>Modifica i testi della pagina: <%= @page_name_in_heading %></h2>

<%= link_to "back", :back, class: "btn" %>
<hr>

<div>
	<%= form_for @texts, url: { action: 'update_texts' } do |f| %>
		<%= render 'shared/error_messages', object: f.object %>

		<%= f.hidden_field :page %>

		<%= f.label :title, 'Titolo nell\'header rosso' %>
		<%= f.text_field :title %>

		<%= f.label :heading, 'Heading della pagina' %>
		<%= f.text_field :heading %>

		<%= f.label :body, 'Testo in alto' %>
		<%= f.text_area :body, rows: 8 %>

		<%= f.label :body, 'Testo in basso' %>
		<%= f.text_area :body2, rows: 8 %>

		<% if @texts.eula_text %>
			<%= f.label :eula_text, 'Testo della checkbox eula/privacy' %>
			<%= f.text_area :eula_text, rows: 2 %>
		<% end %>

		<%= f.submit 'Salva', class: 'btn btn-primary btn_tom' %>
	<% end %>

</div>